#!/usr/bin/env node
// Writes conformance/cases/<name>.json from the Node implementation itself (SPEC.md 16.2):
// every `expected` is what the real Node function returned for that `input`, never typed by hand.
// Run from anywhere with `node conformance/generate.mjs`; the output is deterministic, so a
// second run must leave `git status conformance/cases` unchanged.
//
// That only holds on the reference runtime: several expected values come from Node itself
// (util.parseEnv, toFixed, localeCompare), and parseEnv changed within the 22.x line. So the
// generator refuses to run on any Node but REFERENCE_NODE. `--force` runs it anyway, to re-baseline
// on purpose: change REFERENCE_NODE, SPEC.md (header and 16.2) and conformance/cases/README.md in
// the same commit.
import { mkdirSync, mkdtempSync, readdirSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { encode } from "./generator/tagged.mjs";

// The static imports above have no side effects, so this still runs before anything is written.
const REFERENCE_NODE = "24.21";
if (!process.versions.node.startsWith(`${REFERENCE_NODE}.`) && !process.argv.includes("--force")) {
  console.error(
    `conformance/generate.mjs: the golden cases are generated by Node ${REFERENCE_NODE}.x (SPEC.md 16.2); ` +
      `this is Node ${process.versions.node}. Run it under Node ${REFERENCE_NODE}, or pass --force to ` +
      "re-baseline deliberately and update SPEC.md and conformance/cases/README.md in the same commit.",
  );
  process.exit(1);
}

const here = fileURLToPath(new URL(".", import.meta.url));
const casesDir = join(here, "cases");

// status.mjs and settings.mjs bind the status directory when they load, and the first status write
// prunes week-old files there. Point it at a throwaway directory before anything imports them, so
// generating cases can never touch a live session's files.
const statusDir = mkdtempSync(join(tmpdir(), "jev-conformance-gen-"));
process.env.JEV_STATUS_DIR = statusDir;
process.on("exit", () => rmSync(statusDir, { recursive: true, force: true }));
// The Jev client reads these once, lazily; the jev-request cases stub fetch, so the key is fake.
process.env.JEV_API_KEY = "conformance-test-key";
delete process.env.TYPESAFE_API_KEY;
delete process.env.TYPESAFE_BASE_URL;
delete process.env.TYPESAFE_DEFAULT_MODEL;
delete process.env.JEV_DEBUG;
delete process.env.JEV_DUMP;

const node = (name) => import(new URL(`../node/src/${name}.mjs`, import.meta.url));
const ctx = {
  root: join(here, ".."),
  statusDir,
  config: await node("config"),
  policy: await node("policy"),
  proxy: await node("proxy"),
  status: await node("status"),
  router: await node("router"),
  reasons: await node("reasons"),
  icons: await node("icons"),
  legend: await node("legend"),
  explain: await node("explain"),
  modelNames: await node("model-names"),
  worktree: await node("worktree"),
  update: await node("update"),
  launch: await node("launch"),
  calibration: await import(new URL("../node/scripts/calibration-cases.mjs", import.meta.url)),
};

// One group at a time: the status group pins Date.now and the network group replaces fetch.
const groups = [];
for (const name of ["policy", "proxy", "status", "display", "misc", "json", "network"]) {
  groups.push(await (await import(`./generator/${name}.mjs`)).default(ctx));
}

mkdirSync(casesDir, { recursive: true });
const written = new Set();
for (const group of groups) {
  for (const [file, cases] of Object.entries(group)) {
    if (written.has(file)) throw new Error(`case file ${file} produced twice`);
    const names = new Set();
    const out = cases.map(({ name, input, expected }) => {
      if (names.has(name)) throw new Error(`${file}: duplicate case name ${name}`);
      names.add(name);
      return { name, input: encode(input), expected: encode(expected) };
    });
    writeFileSync(join(casesDir, `${file}.json`), `${JSON.stringify(out, null, 2)}\n`);
    written.add(file);
    console.log(`${file}.json: ${out.length} cases`);
  }
}
// A case file the generator no longer produces must not linger and be trusted by a port.
for (const name of readdirSync(casesDir)) {
  if (name.endsWith(".json") && !written.has(name.slice(0, -5))) unlinkSync(join(casesDir, name));
}
